# Generated by Django 2.2.1 on 2019-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertComments',
            fields=[
                ('cmtid', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.IntegerField()),
                ('eproblem', models.TextField(blank=True, null=True)),
                ('ecomment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expert_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertInfo',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('esex', models.CharField(max_length=2)),
                ('emobile', models.CharField(blank=True, max_length=50, null=True)),
                ('eemail', models.CharField(blank=True, max_length=80, null=True)),
                ('etrade', models.CharField(blank=True, max_length=150, null=True)),
                ('esubtrade', models.CharField(blank=True, max_length=150, null=True)),
                ('ebirthday', models.DateField(blank=True, null=True)),
                ('elandline', models.CharField(blank=True, max_length=50, null=True)),
                ('elocation', models.CharField(blank=True, max_length=150, null=True)),
                ('emsn', models.CharField(blank=True, max_length=80, null=True)),
                ('eqq', models.CharField(blank=True, max_length=50, null=True)),
                ('ephoto', models.CharField(blank=True, max_length=20, null=True)),
                ('estate', models.IntegerField(blank=True, null=True)),
                ('ecomefrom', models.TextField(blank=True, null=True)),
                ('eremark', models.TextField(blank=True, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('addtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expert_info',
                'ordering': ('-addtime',),
                'managed': False,
            },
        ),
    ]
